# Generated by Django 4.0.5 on 2022-08-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contributor",
            name="permission",
            field=models.CharField(
                choices=[("ALL ACCESS", "ALL ACCESS"), ("RESTRICTED", "RESTRICTED")],
                default="restricted",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="created_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
