# Generated by Django 4.0.5 on 2022-09-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_contributor_permission_alter_issue_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='permission',
            field=models.CharField(choices=[('ALL ACCESS', 'ALL ACCESS'), ('RESTRICTED', 'RESTRICTED')], default='ALL ACCESS', max_length=50),
        ),
    ]
